"""Second migration

Revision ID: f31b7881acb7
Revises: e58f5f694746
Create Date: 2023-11-21 13:24:40.154243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31b7881acb7'
down_revision = 'e58f5f694746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
